### ISSUE TITLE
Can we have more details?

### ISSUE THREAD

**Issue by vinaymavi** [pagesource/xt-techradar#4]
Can we have more details?
what is xt-techradar?
how a member can contribute?
@areai51

**Comment by kumarranjansingh** [comment]
Xt - techradar will show the upcoming technologies in the world of web and
mobile and what are the technologies we can start investing in and what are
the technologies which is not in demand any more and should move to
alternative for that.

To help in this project, any one can raise pull request for any issues or
defect and specifically the data folder which contains radar-data.json to
update the radar with the technologies that you want to be added in the
radar and then LT can review it to add it in the radar.
The data which is currently shown(xt-techradar.com) which not appropriate
at few places.

Thanks

**Comment by vinaymavi** [comment]
Thank you @kumarranjansingh  for details.
